package gateway

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.82

import (
	"context"

	graphql1 "github.com/jackthomas00/polaris/internal/gateway/graphql"
	"github.com/jackthomas00/polaris/internal/gateway/graphql/generated"
)

// RecordUsage is the resolver for the recordUsage field.
func (r *mutationResolver) RecordUsage(ctx context.Context, metric string, quantity int) (bool, error) {
	return r.Resolver.RecordUsage(ctx, metric, quantity)
}

// GenerateInvoice is the resolver for the generateInvoice field.
func (r *mutationResolver) GenerateInvoice(ctx context.Context, periodStart string, periodEnd string) (*graphql1.Invoice, error) {
	invoice, err := r.Resolver.GenerateInvoice(ctx, periodStart, periodEnd)
	if err != nil {
		return nil, err
	}
	if invoice == nil {
		return nil, nil
	}
	return &graphql1.Invoice{
		ID:          invoice.ID,
		TotalAmount: invoice.TotalAmount,
		Status:      invoice.Status,
		PeriodStart: invoice.PeriodStart,
		PeriodEnd:   invoice.PeriodEnd,
	}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*graphql1.Organization, error) {
	org, err := r.Resolver.Me(ctx)
	if err != nil {
		return nil, err
	}
	if org == nil {
		return nil, nil
	}
	return &graphql1.Organization{
		ID:   org.ID,
		Name: org.Name,
	}, nil
}

// Usage is the resolver for the usage field.
func (r *queryResolver) Usage(ctx context.Context, metric string) ([]*graphql1.UsageAggregate, error) {
	aggregates, err := r.Resolver.Usage(ctx, metric)
	if err != nil {
		return nil, err
	}
	result := make([]*graphql1.UsageAggregate, len(aggregates))
	for i, agg := range aggregates {
		result[i] = &graphql1.UsageAggregate{
			Metric:      agg.Metric,
			Total:       agg.Total,
			PeriodStart: agg.PeriodStart,
			PeriodEnd:   agg.PeriodEnd,
		}
	}
	return result, nil
}

// Invoices is the resolver for the invoices field.
func (r *queryResolver) Invoices(ctx context.Context) ([]*graphql1.Invoice, error) {
	invoices, err := r.Resolver.Invoices(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*graphql1.Invoice, len(invoices))
	for i, inv := range invoices {
		result[i] = &graphql1.Invoice{
			ID:          inv.ID,
			TotalAmount: inv.TotalAmount,
			Status:      inv.Status,
			PeriodStart: inv.PeriodStart,
			PeriodEnd:   inv.PeriodEnd,
		}
	}
	return result, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
